### ISSUE TITLE
无法提取带-的词汇？？？

### ISSUE THREAD

**Issue by Yetocome** [maimemo/word-extractor#3]
例如hard-bitten,hard-nosed会被识别为hard一个词汇。
没找到有标准的格式来置入单词，尝试过用\,和\n来分词，结果并没有区别。
貌似这个项目是希望把这个过程黑盒化，但我觉得这样可能无法兼顾一些特殊需求。建议参考quizlet的词库导入，非常灵活的自定义。

**Comment by Celend** [comment]
这是我们的面试题哈，示例程序是很久之前的版本了。你可以下载 墨墨背单词 体验一下，上述单词是能够正常识别的。
